services:

  server:
    container_name: server
    build:
      dockerfile: ./build/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy  # Ensure redis is healthy before starting server
  
  docs:
    container_name: docs
    build:
      dockerfile: ./build/docs.Dockerfile
    ports:
      - "${DOCS_PORT}:6060"
    restart:
      unless-stopped

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass "${REDIS_PASSWORD}" --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "-p", "${REDIS_PORT}", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

networks:
  node_net:
    driver: bridge