services:

  server:
    container_name: server
    build:
      dockerfile: ./build/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    restart: unless-stopped
  
  docs:
    container_name: docs
    build:
      dockerfile: ./build/Dockerfile.docs
    ports:
      - "${DOCS_PORT}:6060"
    restart:
      unless-stopped