# fly.toml app configuration file generated for backendproject on 2024-08-10T10:03:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendproject'
primary_region = 'gru'

[build]
  dockerfile = "./build/release.Dockerfile"
  [build.args]
    GO_VERSION = '1.23'

[env]
  SERVER_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
